-- Script that lists all records of the table second_table of the database hbtn_0c_0 in my MySQL server.
-- Query that lists all records of the table second_table of the database hbtn_0c_0 in my MySQL server.
